### ISSUE TITLE
Want to handle table names like Rails

### ISSUE THREAD

**Issue by nacika-ins** [KenjiOhtsuka/harmonica#113]
**Is your feature request related to a problem? Please describe.**

I was using a table structure as of Rails.
It is like the following.

```
tableName:  users
reference_id:  user_id
```

However, In harmonica, when I specify the plural table name for `refer`, it becomes `users_id`.

**Describe the solution you'd like**

Should:
```
refer("users", columnName: "user_id", referencedColumnName: "id")
```

**Describe alternatives you've considered**

```
integer("user_id", nullable = false)
addForeignKey("organizations", "user_id", "users", "id")
```

**Comment by KenjiOhtsuka** [comment]
@nacika-ins 
As far as I remember, when we use Spring Boot `@Entity` as follows:

```kotlin
@Entity
@EntityListeners(AuditingEntityListener::class)
class Task {
    @Id
    @SequenceGenerator(
        name = "task_id_seq",
        sequenceName = "task_id_seq",
        allocationSize = 1
    )
    @GeneratedValue(
        strategy = GenerationType.SEQUENCE,
        generator = "task_id_seq"
    )
    var id: Long? = null
    
    var name: String? = null
    
    @CreatedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false, updatable = false)
    var createdAt: Date? = null
 
    @LastModifiedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false, updatable = false)
    var updatedAt: Date? = null
}
```

Spring automatically uses the table "task", not "tasks".
On the contrary, Rails model `task.rb` uses "tasks" table, for example.

So I thought I mustn't change single form table name to plural form.

**Comment by KenjiOhtsuka** [comment]
@nacika-ins 
Sorry, I may have misunderstood you post.

**Comment by KenjiOhtsuka** [comment]
I released the new version.
from 1.1.19, `refer` method can work like Rails migration.

For that, you have to add configuration to `buid.gradle`.
https://github.com/KenjiOhtsuka/harmonica/wiki/Configuration

If you have any trouble, please let me know.

Thank you.

**Comment by KenjiOhtsuka** [comment]
@nacika-ins 

I released the new version.
from 1.1.19, refer method can work like Rails migration.

For that, you have to add configuration to buid.gradle.
https://github.com/KenjiOhtsuka/harmonica/wiki/Configuration

If you have any trouble, please let me know.

Thank you.
