### ISSUE TITLE
Clear and concise documentation on Exposed

### ISSUE THREAD

**Issue by Wnzebkhan** [KenjiOhtsuka/harmonica#115]
**Is your feature request related to a problem? Please describe.**
I would like samples as to how to add columns to a table which already exists and the model is already defined of. So for example, lets say I have a table with 2 columns, and I already have an Exposed-model of it. 

During programming, another column is added to this table, and this has to be migrated. How would I write this in the migration-file using Exposed? In other words: How do I alter tables in exposed?

**Describe the solution you'd like**
Clear samples on altering tables.

Thank you for your cooperation!

**Comment by KenjiOhtsuka** [comment]
@Wnzebkhan 

Please ask in exposed GitHub page.
https://github.com/JetBrains/Exposed/issues
