### ISSUE TITLE
Clear documentation on altering tables through Exposed

### ISSUE THREAD

**Issue by Wnzebkhan** [KenjiOhtsuka/harmonica#116]
**Is your feature request related to a problem? Please describe.**
Right now, it is hard to find examples of code for certain database-changes using Exposed, such as adding a column to an existing table, dropping a column from an existing table, adding/removing foreign-key constraints etc. 

**Describe the solution you'd like**
A clear and concise documentation as to how combine Exposed-functions to alter tables and the schema itself.

Thank you for your cooperation!

**Comment by KenjiOhtsuka** [comment]
@Wnzebkhan 

Do you mean you want to see how to use Exposed, right?
If yes, isn't Exposed document clear?
https://github.com/JetBrains/Exposed

### Example with Harmonica

```
import org.jetbrains.exposed.sql.SchemaUtils.drop
import org.jetbrains.exposed.sql.SchemaUtils.create
import org.jetbrains.exposed.sql.Table

object Cities : Table() {
    val id = integer("id").autoIncrement().primaryKey() // Column<Int>
}

class M20180624011127704_HolloWorld : AbstractMigration() {
    override fun up() {
        create(Cities)
    }

    override fun down() {
        drop(Cities)
    }
}
```
https://github.com/KenjiOhtsuka/harmonica/wiki/Jarmonica-Usage
