### ISSUE TITLE
Plugin with id 'jarmonica' not found.

### ISSUE THREAD

**Issue by PaulMuriithi** [KenjiOhtsuka/harmonica#40]
**Describe the bug**
I am trying to setup a project using the [wiki](https://github.com/KenjiOhtsuka/harmonica/wiki/Jarmonica-Usage) on Intellij but it keeps failing with the error Plugin with id 'jarmonica' not found.

**To Reproduce**
Clone the sample repo https://github.com/PaulMuriithi/HelloHarmonica
Import it in Intellij and try to build it

**Expected behavior**
Building ok which does not happen

**Environment:**
IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

**Comment by PaulMuriithi** [comment]
This is a great tool and I hope to contribute to it since I was looking to build something similar

**Comment by KenjiOhtsuka** [comment]
@PaulMuriithi 

Hello.
Please use latest harmonica.
It is version 1.0.13.

Sorry for delaying wiki updating.

**Comment by KenjiOhtsuka** [comment]
I updated wiki. Sorry to be late.

**Comment by PaulMuriithi** [comment]
Cool, that worked!

Thanks
